name = "NASAPrecipitation"
uuid = "a018b980-0677-41c0-b9a4-7f34595c2b14"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
